//Set ve.registry.localisation defaults
ve.registry.localisation = {
	//FileExplorer EN-GB
	FileExplorer_are_you_sure_delete: "Are you sure you want to delete the following files?<br><br>£1£<br><br>This action cannot be undone!",
	FileExplorer_are_you_sure_copy_paste: "Are you sure you want to copy/paste £1£ file(s) to £2£?",
	FileExplorer_are_you_sure_load: "Are you sure you want to load £1£?",
	FileExplorer_back: "Back",
	FileExplorer_cannot_create_unnamed_folder: "You cannot create a folder with no name.",
	FileExplorer_clear_clipboard: "Clear Clipboard",
	FileExplorer_clipboard: "Clipboard",
	FileExplorer_clipboard_is_empty: "Clipboard is empty.",
	FileExplorer_create_a_new_file: "Create a new file:",
	FileExplorer_create_new_file: "Create New File",
	FileExplorer_create_new_folder: "Create New Folder",
	FileExplorer_create_a_new_folder: "Create a new folder:",
	FileExplorer_created_empty_text_file: "Created empty text file at: £1£",
	FileExplorer_cut_paste_files: "Cut/Paste £1£ files",
	FileExplorer_confirm: "Confirm",
	FileExplorer_copied_elements_to_clipboard: "Copied £1£ elements to clipboard.",
	FileExplorer_copy_selected: "Copy Selected",
	FileExplorer_delete_files: "Delete £1£ files",
	FileExplorer_do_you_want_to_overwrite_file: "File already exists. Do you want to overwrite it?",
	FileExplorer_error_load: "Error upon loading file £1£: £2£",
	FileExplorer_error_load_save_file: "Error loading savefile",
	FileExplorer_load_save_file: "Load Savefile",
	FileExplorer_loaded_save_file: "Loaded savefile £1£",
	FileExplorer_move_files: "Move £1£ files",
	FileExplorer_paste_clipboard: "Paste Clipboard",
	FileExplorer_paste_files: "Paste £1£ files",
	FileExplorer_rename: "Rename",
	FileExplorer_save_file: "Save File",
	FileExplorer_save_file_as: "Save file as:",
	FileExplorer_select: "Select",
	FileExplorer_specified_file_path_already_exists: "The specified path already exists as a file! Delete it first before creating a new file with the same name.",
	FileExplorer_successfully_saved_file_as: "Successfully saved file as: £1£",
	
	//FileExplorer (File Operations) EN-GB
	FileExplorer_copying_files_to: "Copying £1£ file(s) to £2£",
	FileExplorer_copying_to: "Copying £1£ to £2£",
	FileExplorer_deleting_files: "Deleting £1£ file(s)",
	FileExplorer_deleting_path: "Deleting £1£",
	FileExplorer_done: "Done",
	FileExplorer_error_could_not_be_renamed: "ERROR: £1£ could not be renamed: £2£",
	FileExplorer_eta_remaining: "£1£% - £2£ remaining",
	FileExplorer_finished_moving_files: "Finished moving files",
	FileExplorer_of_progress: "(£1£ of £2£)",
	FileExplorer_moved_files: "Finished moving £1£ file(s) to £2£",
	FileExplorer_rename_file: "Rename File",
	FileExplorer_rename_file_to: "Rename file £1£ to:",
	
	//Hierarchy EN-GB
	Hierarchy_search_for_item: "Search for item ...",
	
	//ScriptManager EN-GB
	ScriptManager_are_you_sure_clear_console: "Are you sure you want to clear the current console?",
	ScriptManager_clear_blockly_on_error: "Clear Blockly on error",
	ScriptManager_clear_console: "Clear Console",
	ScriptManager_codemirror_theme: "Codemirror Theme",
	ScriptManager_console: "Console",
	ScriptManager_could_not_load_settings: "Could not load non-ScriptManager settings.",
	ScriptManager_display_load_errors: "Display load errors",
	ScriptManager_editor_theme: "Editor Theme",
	ScriptManager_enter_console_command: "Enter console command ...",
	ScriptManager_error_compatibility: "Are you sure this file is £1£ compatible? Blockly has been disabled, and the file is only editable via CodeMirror.",
	ScriptManager_error_loading_settings: "Error loading settings",
	ScriptManager_error_reading_file: "Error Reading File",
	ScriptManager_help: "Help",
	ScriptManager_help_menu: "Help Menu:",
	ScriptManager_hide_blockly: "Hide Blockly",
	ScriptManager_hide_show_blockly: "Hide/show Blockly workspace on error",
	ScriptManager_load_settings: "Load Settings",
	ScriptManager_none: "None",
	ScriptManager_note: "Note:",
	ScriptManager_keybinds: "Keybinds",
	ScriptManager_prints_help_information: "Prints help information.",
	ScriptManager_run: "Run",
	ScriptManager_run_current_file: "Run Current File",
	ScriptManager_run_settings: "Run Settings:",
	ScriptManager_save_settings: "Save Settings",
	ScriptManager_saved_settings: "Saved settings to £1£!",
	ScriptManager_send: "Send",
	ScriptManager_settings: "Settings",
	ScriptManager_show_blockly: "Show Blockly",
	ScriptManager_stack_trace: "Stack Trace:",
	ScriptManager_theme_default: "Default",
	ScriptManager_theme_light: "Light",
	ScriptManager_trust_warning: "Make sure you trust the code you are about to run before executing it.",
	ScriptManager_view: "View",
	ScriptManager_view_file_explorer: "View File Explorer"
};